# Generated by Django 4.1 on 2022-09-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('answer', models.DecimalField(decimal_places=3, max_digits=13)),
                ('position', models.IntegerField()),
                ('visible', models.IntegerField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rel', to='question_list.questionlist')),
            ],
        ),
    ]
