# Generated by Django 4.1 on 2022-09-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0002_alter_questionlist_description_and_more'),
        ('question_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rel', to='question_list.questionlist'),
        ),
    ]
