# Generated by Django 4.1 on 2022-09-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_detail', '0002_alter_question_question_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_visibility',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
