# Generated by Django 4.1 on 2022-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
